#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "webrecon v1.0"
    echo "https://github.com/byfranke"
    echo "Usage: $0 <URL>"
    exit 1
fi

wget -m -e robots=off "$1"

echo -e "\nAnalyzing Page..."

output_file="results_$(echo $1 | sed 's/[^a-zA-Z0-9]//g').txt"

grep -rinE -h --color 'username|user_name|userid|user_id|login|password|passwd|pass_word|pwd|secret|auth|access_token' ./ | while read line; do
    echo -e "$line\n" >> "$output_file"
done
