#!/bin/bash

if [ "$#" -eq 0 ]; then
    echo "scan-web v1.0"
    echo "https://github.com/byfranke"
    echo "Example: sudo scan-web IP"
    exit 1
fi
echo -e "\nWhatWeb"
whatweb "$1"

echo -e "\n\nWebrecon"
webrecon "$1"

echo -e "\n\nNmap"
sudo nmap -v -D RND:25 -sS -top-ports=25 --open -T2 -Pn "$1"

echo -e "\n\nDirsearch"
dirsearch -u "$1" -i "200,301,302,401" --random-agent

echo -e "\nCurl"
curl -v -X OPTIONS "$1"

echo -e "\n\nNuclei"
nuclei-hunter "$1" http >> nuclei_"$1"_vuln.txt

echo -e "\n\nNmap-Vuln"
sudo nmap -v --open -sSCV -Pn -O "$1" --script=vuln >> nmap_"$1"_vuln.txt

echo -e "\n\n$0 Completed"
