#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "nuclei-hunter v1.0"
    echo "https://github.com/byfranke"
    echo "Usage: $0 [domain] [template]"
    echo "Example: $0 example.com vulnerabilities"
    exit 1
fi

OUTPUT_DIR="$HOME/Documents/Nuclei"
TEMPLATE_PATH="$HOME/.local/nuclei-templates"

[ -d "$OUTPUT_DIR" ] || mkdir -p "$OUTPUT_DIR"

date '+Date: %d/%m/%Y Time: %H:%M:%S' >> "$OUTPUT_DIR/$1.txt"

echo "-------------------------------" >> "$OUTPUT_DIR/$1.txt"

echo -e "\n" >> "$OUTPUT_DIR/$1.txt"
echo -e "\n" >> "$OUTPUT_DIR/$1.txt"

subfinder -d $1 | nuclei -t "$TEMPLATE_PATH/$2" -c 50 -o "$OUTPUT_DIR/$1.txt"
