#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "scan-websilence v1.0"
    echo "https://github.com/byfranke"
    echo "Usage: $0 <URL/IP>"
    exit 1
fi

sudo nmap -v -D RND:25 -sS -top-ports=25 --open -T2 -Pn $1
